name: scan
on:
  workflow_dispatch:
  schedule:
    - cron: "18 12 * * *" #runs at 00:18 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Requirements
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Scan Pages
        run: |
          python pagediff.py

      - name: Commit Boring Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Nightly Scan
          message: 'Only Boring Changes Found'

      - name: Move Staged Important Changes
        run: |
          bash move_staged.sh

      - name: Commit Important Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Nightly Scan
          message: 'Important Changes Found! (maybe) @rebeccaeroy @JamesMaroney'
